apply plugin: "com.android.application"

android {
    namespace 'com.shatteredpixel.shatteredpixeldungeon.android'
    compileSdk rootProject.ext.appAndroidCompileSDK

    defaultConfig {
        applicationId rootProject.ext.appPackageName
        minSdk rootProject.ext.appAndroidMinSDK
        targetSdk rootProject.ext.appAndroidTargetSDK
        versionCode rootProject.ext.appVersionCode
        versionName rootProject.ext.appVersionName
        multiDexEnabled true
    }

    compileOptions {
        sourceCompatibility rootProject.ext.appJavaCompatibility
        targetCompatibility rootProject.ext.appJavaCompatibility
    }

    sourceSets {
        main {
            manifest.srcFile 'AndroidManifest.xml'
            java.srcDirs = ['src']
            aidl.srcDirs = ['src']
            renderscript.srcDirs = ['src']
            res.srcDirs = ['res']
            assets.srcDirs = ['assets']
            jniLibs.srcDirs = ['libs']
        }
    }
    
    packaging {
        resources {
            excludes += ['META-INF/robovm/ios/robovm.xml']
        }
    }
}

dependencies {
    implementation project(':core')
    implementation "com.badlogicgames.gdx:gdx-backend-android:$gdxVersion"
    natives "com.badlogicgames.gdx:gdx-platform:$gdxVersion:arm64-v8a"
    natives "com.badlogicgames.gdx:gdx-platform:$gdxVersion:armeabi-v7a"
    natives "com.badlogicgames.gdx:gdx-platform:$gdxVersion:x86_64"
    implementation "com.badlogicgames.gdx:gdx-freetype:$gdxVersion"
    natives "com.badlogicgames.gdx:gdx-freetype-platform:$gdxVersion:arm64-v8a"
    natives "com.badlogicgames.gdx:gdx-freetype-platform:$gdxVersion:armeabi-v7a"
    natives "com.badlogicgames.gdx:gdx-freetype-platform:$gdxVersion:x86_64"
    implementation "com.badlogicgames.gdx:gdx-controllers:gdx-controllers-android:$gdxVersion"
    implementation 'com.google.android.gms:play-services-ads:22.5.0'
}
